development:
    adapter: mysql2
    database: transunion_rails
    encoding: utf8
    username: rails
    password: rails
    host: localhost

test: #&test
    adapter: mysql2
    database: transunion_rails_test
    encoding: utf8
    username: rails
    password: rails
    host: localhost

production:
    adapter: mysql
    database: firstrails
    encoding: utf8
    username: rails
    password: rails
    host: localhost

#cucumber:
#  <<: *test
