development:
    adapter: mysql2
    database: test
    encoding: utf8
    username: test
    password: test
    host: localhost

test: #&test
    adapter: mysql2
    database: test_test
    encoding: utf8
    username: test
    password: test
    host: localhost

production:
    adapter: mysql
    database: test
    encoding: utf8
    username: rails
    password: rails
    host: localhost

#cucumber:
#  <<: *test
